# Generated by Django 6.0.6 on 2026-06-12 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_patients', models.IntegerField(default=0)),
                ('patients_served', models.IntegerField(default=0)),
                ('patients_cancelled', models.IntegerField(default=0)),
                ('average_wait_time', models.FloatField(default=0)),
                ('average_consultation_time', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_number', models.PositiveIntegerField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField()),
                ('phone_number', models.CharField(max_length=15)),
                ('consultation_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('serving', 'Serving'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='waiting', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('estimated_wait_time', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['token_number'],
            },
        ),
        migrations.CreateModel(
            name='QueueSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_consultation_time', models.PositiveIntegerField(default=10, help_text='Average consultation time in minutes')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duration_minutes', models.FloatField()),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='queue_app.patient')),
            ],
        ),
    ]
