# Generated by Django 6.0.6 on 2026-06-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='queuesettings',
            name='queue_active',
            field=models.BooleanField(default=True),
        ),
    ]
