# Generated by Django 6.0.6 on 2026-06-14 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0002_queuesettings_queue_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('urgent', 'Urgent'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
    ]
