# Generated by Django 6.0.6 on 2026-06-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue_app', '0003_patient_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='priority_rank',
            field=models.IntegerField(default=1),
        ),
    ]
